### ISSUE TITLE
Generating the bitstream file for the Nexys A7 50T

### ISSUE THREAD

**Issue by vincentabraham** [Digilent/Nexys-A7-50T-OOB#1]
Is there a way that I could generate the bitstream file only through the source files without connecting it to the board ? I need the bitstream file to later program the FPGA on platform IO.

**Comment by artvvb** [comment]
You don't need to connect to the board to get the bitstream. The file is included in the release, which you can run through in File Explorer or your OS's equivalent.

**Comment by vincentabraham** [comment]
Which release are you referring to? I couldn't find the bitstream file
(.bit) anywhere in the GitHub repo.

**Comment by vincentabraham** [comment]
I just need the bitstream file for the board so I could later program it
using PlatformIO.

**Comment by artvvb** [comment]
The 2018.2 release is here (https://github.com/Digilent/Nexys-A7-50T-OOB/releases/tag/v2018.2-1). You don't need Vivado 2018.2 to get to the bitstream, it's in the vivado_proj\Nexys-A7-50T-OOB.runs\impl_1 directory of the ZIP file.

**Comment by vincentabraham** [comment]
Okay I found it. Thank you.

**Comment by vincentabraham** [comment]
I want to program the Nexys A7 50T board through PlatformIO by connecting
it to my PC. What sort of drivers and other software would I require ?
